Repository AntelopeIO/leap, pull requests merged in 2022-09, with the labels that each got.

#125 [3.1 -> main] Allow for larger subjective CPU billing amounts
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/controller.hpp
  libraries/chain/include/eosio/chain/transaction_context.hpp
  plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
  plugins/producer_plugin/include/eosio/producer_plugin/subjective_billing.hpp
  plugins/producer_plugin/producer_plugin.cpp
Labels: OCI

#128 [3.1] Test: verify on the correct fork before verifying trx status
  tests/trx_finality_status_forked_test.py
Labels: OCI

#133 [3.1 -> main] Test: verify on the correct fork before verifying trx status
  tests/trx_finality_status_forked_test.py
Labels: OCI

#96 [3.2] Remove hardcoded 10ms limit for chain_api_plugin calls
  plugins/chain_api_plugin/chain_api_plugin.cpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
  plugins/chain_plugin/test/test_chain_plugin.cpp
  plugins/db_size_api_plugin/db_size_api_plugin.cpp
  plugins/http_plugin/http_plugin.cpp
  plugins/http_plugin/include/eosio/http_plugin/common.hpp
  plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp
  plugins/login_plugin/login_plugin.cpp
  plugins/net_api_plugin/net_api_plugin.cpp
  plugins/producer_api_plugin/producer_api_plugin.cpp
  plugins/test_control_api_plugin/test_control_api_plugin.cpp
  plugins/trace_api_plugin/trace_api_plugin.cpp
  plugins/txn_test_gen_plugin/txn_test_gen_plugin.cpp
  plugins/wallet_api_plugin/wallet_api_plugin.cpp
  programs/cleos/main.cpp
  programs/keosd/main.cpp
  tests/chain_plugin_tests.cpp
  tests/get_producers_tests.cpp
  tests/get_table_seckey_tests.cpp
  tests/get_table_tests.cpp
Labels: OCI

#146 [3.2] Fix multithreaded Snapshot test Failure
  libraries/testing/include/eosio/testing/snapshot_suites.hpp
  unittests/snapshot_tests.cpp
Labels: OCI

#135 [3.1] net_plugin fix startup issue when peer does not have requested blocks
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#153 [3.1 -> main] net_plugin fix startup issue when peer does not have requested blocks
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#166 [3.2] Remove initial_chain_id in genesis.json as it is not supported.
  tutorials/bios-boot-tutorial/genesis.json
Labels: OCI

#158 [3.2] cleos: only unpack action data when explicitly asked
  programs/cleos/main.cpp
  tests/nodeos_run_test.py
Labels: OCI

#175 [3.2] Do not apply 3-strike rule when subjective billing is disabled
  plugins/producer_plugin/producer_plugin.cpp
Labels: OCI

#172 [3.2] switch parallel tests to new runner type
  .github/workflows/build.yaml
Labels: cicd

#173 [3.2] enable all tests for Ubuntu 22; NP & LR tests for Ubuntu 18
  .github/actions/parallel-ctest-containers/action.yml
  .github/actions/parallel-ctest-containers/dist/index.mjs
  .github/actions/parallel-ctest-containers/main.mjs
  .github/actions/parallel-ctest-containers/package-lock.json
  .github/actions/parallel-ctest-containers/package.json
  .github/workflows/build.yaml
Labels: cicd

#171 Docs: http protocol spec for producer plugin
  plugins/producer_api_plugin/producer.swagger.yaml
Labels: documentation

#185 [3.2] label new issues with 'triage' label and add them to the Team Backlog project as Todo
  .github/workflows/label_new_issues.yaml
Labels: cicd

#183 [3.1] trx_finality_status_forked_test fix
  tests/trx_finality_status_forked_test.py
Labels: OCI

#189 [3.1 -> main] trx_finality_status_forked_test fix
  tests/trx_finality_status_forked_test.py
Labels: OCI

#182 [3.2] Add /v1/chain/get_unapplied_transactions to producer_api_plugin
  libraries/chain/include/eosio/chain/unapplied_transaction_queue.hpp
  plugins/producer_api_plugin/producer.swagger.yaml
  plugins/producer_api_plugin/producer_api_plugin.cpp
  plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
  plugins/producer_plugin/producer_plugin.cpp
  tests/plugin_http_api_test.py
  unittests/unapplied_transaction_queue_tests.cpp
Labels: OCI

#197 [3.2] updated schema references to eosnetwork host
  plugins/chain_api_plugin/chain.swagger.yaml
  plugins/net_api_plugin/net.swagger.yaml
  plugins/producer_api_plugin/producer.swagger.yaml
  plugins/test_control_api_plugin/test_control.swagger.yaml
  plugins/trace_api_plugin/trace_api.swagger.yaml
Labels: documentation

#204 [3.1] Curate eosio refs, and github, eosnetwork links (docs)
  docs/00_install/01_build-from-source/00_build-unsupported-os.md
  docs/00_install/01_build-from-source/index.md
  docs/00_install/index.md
  docs/01_nodeos/02_usage/02_node-setups/00_producing-node.md
  docs/01_nodeos/02_usage/02_node-setups/01_non-producing-node.md
  docs/01_nodeos/02_usage/03_development-environment/00_local-single-node-testnet.md
  docs/01_nodeos/02_usage/03_development-environment/01_local-multi-node-testnet.md
  docs/01_nodeos/02_usage/03_development-environment/index.md
  docs/01_nodeos/03_plugins/chain_api_plugin/api-reference/index.md
  docs/01_nodeos/03_plugins/chain_plugin/index.md
  docs/01_nodeos/03_plugins/db_size_api_plugin/api-reference/index.md
  docs/01_nodeos/03_plugins/login_plugin/index.md
  docs/01_nodeos/03_plugins/net_api_plugin/api-reference/index.md
  docs/01_nodeos/03_plugins/net_api_plugin/index.md
  docs/01_nodeos/03_plugins/producer_api_plugin/api-reference/index.md
  docs/01_nodeos/03_plugins/producer_plugin/index.md
  docs/01_nodeos/03_plugins/state_history_plugin/10_how-to-fast-start-without-old-history.md
  docs/01_nodeos/03_plugins/state_history_plugin/20_how-to-replay-or-resync-with-full-history.md
  docs/01_nodeos/03_plugins/state_history_plugin/30_how-to-create-snapshot-with-full-history.md
  docs/01_nodeos/03_plugins/state_history_plugin/40_how-to-restore-snapshot-with-full-history.md
  docs/01_nodeos/03_plugins/trace_api_plugin/api-reference/index.md
  docs/01_nodeos/03_plugins/trace_api_plugin/index.md
  docs/01_nodeos/03_plugins/txn_test_gen_plugin/index.md
  docs/01_nodeos/06_logging/index.md
  docs/01_nodeos/07_concepts/05_storage-and-read-modes.md
  docs/01_nodeos/07_concepts/10_context-free-data/index.md
  docs/01_nodeos/08_troubleshooting/index.md
  docs/01_nodeos/index.md
  docs/02_cleos/02_how-to-guides/how-to-create-a-wallet.md
  docs/02_cleos/02_how-to-guides/how-to-create-an-account.md
  docs/02_cleos/02_how-to-guides/how-to-create-key-pairs.md
  docs/02_cleos/02_how-to-guides/how-to-delegate-CPU-resource.md
  docs/02_cleos/02_how-to-guides/how-to-delegate-net-resource.md
  docs/02_cleos/02_how-to-guides/how-to-deploy-a-smart-contract.md
  docs/02_cleos/02_how-to-guides/how-to-get-account-information.md
  docs/02_cleos/02_how-to-guides/how-to-get-block-information.md
  docs/02_cleos/02_how-to-guides/how-to-get-transaction-information.md
  docs/02_cleos/02_how-to-guides/how-to-import-a-key.md
  docs/02_cleos/02_how-to-guides/how-to-list-all-key-pairs.md
  docs/02_cleos/03_command-reference/create/account.md
  docs/02_cleos/03_command-reference/net/connect.md
  docs/02_cleos/03_command-reference/net/disconnect.md
  docs/02_cleos/03_command-reference/net/peers.md
  docs/02_cleos/03_command-reference/net/status.md
  docs/02_cleos/03_command-reference/set/set-account.md
  docs/02_cleos/04_troubleshooting.md
  docs/02_cleos/index.md
  docs/03_keosd/index.md
  docs/10_utilities/index.md
  docs/index.md
Labels: documentation

#219 [3.2] Log std::exception while handling API calls at debug level
  plugins/http_plugin/http_plugin.cpp
Labels: OCI

#220 [3.1 -> main] Fix nodeos_retry_transaction_test.py
  tests/nodeos_retry_transaction_test.py
Labels: OCI

#211 [3.1] when uploading failure logs, ignore missing files
  .github/workflows/build.yaml
Labels: cicd

#221 [3.2] always run the long running tests, including for pull requests
  .github/workflows/build.yaml
Labels: cicd

#226 [3.1] Test fix: wait for system init to be in block
  tests/Cluster.py
  tests/nodeos_contrl_c_test.py
Labels: OCI

#224 [3.1] updated trace_api openapi documentation
  plugins/trace_api_plugin/trace_api.swagger.yaml
Labels: documentation

#240 [3.1 -> main] updated trace_api openapi documentation
  plugins/trace_api_plugin/trace_api.swagger.yaml
Labels: documentation

#245 [3.1] Remove #pragma(s) to ignore warnings
  libraries/chain/apply_context.cpp
  libraries/chain/controller.cpp
  libraries/chain/eosio_contract.cpp
  libraries/chain/fork_database.cpp
  libraries/chain/include/eosio/chain/config.hpp
  libraries/chain/webassembly/softfloat.cpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/net_plugin/net_plugin.cpp
  plugins/trace_api_plugin/store_provider.cpp
  plugins/trace_api_plugin/test/test_extraction.cpp
  plugins/trace_api_plugin/test/test_trace_file.cpp
  plugins/trace_api_plugin/trace_api_plugin.cpp
  plugins/txn_test_gen_plugin/txn_test_gen_plugin.cpp
  programs/cleos/main.cpp
  programs/eosio-launcher/main.cpp
  unittests/abi_tests.cpp
  unittests/api_tests.cpp
  unittests/auth_tests.cpp
  unittests/bootseq_tests.cpp
  unittests/deep_mind_tests.cpp
  unittests/delay_tests.cpp
  unittests/snapshot_tests.cpp
  unittests/wasm_config_tests.cpp
  unittests/wasm_tests.cpp
Labels: OCI

#249 [3.1] Increase keosd http-max-response-time-ms for tests
  tests/WalletMgr.py
  tutorials/bios-boot-tutorial/bios-boot-tutorial.py
Labels: OCI

#222 [3.2] Add information about log levels [docs]
  docs/01_nodeos/06_logging/01_logging-levels.md
Labels: documentation, OCI
