Repository AntelopeIO/leap, pull requests merged in 2022-10, with the labels that each got.

#269 [3.2] Fix some clang warnings
  libraries/libfc/include/fc/crypto/blake2.hpp
  libraries/libfc/src/crypto/crc.cpp
  tests/ship_client.cpp
Labels: OCI

#273 [3.1] Fix replay to correctly add trxs into the de-dup list
  libraries/chain/controller.cpp
Labels: OCI

#270 [3.2] Do not log or subjective bill for duplicate trxs
  plugins/producer_plugin/producer_plugin.cpp
Labels: OCI

#307 [3.1] Test fix: trx_finality_status_forked_test.py
  tests/trx_finality_status_forked_test.py
Labels: OCI

#308 [3.1 -> 3.2] Test fix: trx_finality_status_forked_test.py
  tests/trx_finality_status_forked_test.py
Labels: OCI

#309 [3.2 -> main] Test fix: trx_finality_status_forked_test.py
  tests/trx_finality_status_forked_test.py
Labels: OCI

#316 [3.1] Test fix: nodeos_forked_chain_lr_test
  plugins/test_control_plugin/test_control_plugin.cpp
Labels: OCI

#326 [3.2] Return application/json for all http responses including errors
  plugins/chain_api_plugin/chain_api_plugin.cpp
  plugins/http_plugin/http_plugin.cpp
  plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
  plugins/http_plugin/include/eosio/http_plugin/common.hpp
  plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp
Labels: OCI

#322 [3.1] Test fix: api_tests checktime_pause_block_deadline_not_extended_test
  unittests/api_tests.cpp
Labels: OCI

#337 [3.2 -> main] Return application/json for all http responses including errors
  plugins/chain_api_plugin/chain_api_plugin.cpp
  plugins/http_plugin/http_plugin.cpp
  plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
  plugins/http_plugin/include/eosio/http_plugin/common.hpp
  plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp
Labels: OCI

#338 [3.1 -> 3.2] Test fix: api_tests checktime_pause_block_deadline_not_extended_test
  unittests/api_tests.cpp
Labels: OCI

#339 [3.2 -> main] Test fix: api_tests checktime_pause_block_deadline_not_extended_test
  unittests/api_tests.cpp
Labels: OCI

#347 [3.1] SHiP Fix log output
  libraries/state_history/include/eosio/state_history/log.hpp
Labels: OCI

#348 [3.1 -> 3.2] SHiP Fix log output
  libraries/state_history/include/eosio/state_history/log.hpp
Labels: OCI

#349 [3.2 -> main] SHiP Fix log output
  libraries/state_history/include/eosio/state_history/log.hpp
Labels: OCI

#334 [4.0] SHiP: Store initial chain state on startup if state_history_plugin chain state log is empty
  plugins/state_history_plugin/state_history_plugin.cpp
Labels: OCI

#356 [3.1] Remove replay optimization that skips recording transactions in dedup list
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/transaction_context.hpp
  libraries/chain/transaction_context.cpp
Labels: OCI

#365 [3.1 -> 3.2] Remove replay optimization that skips recording transactions in dedup list
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/transaction_context.hpp
  libraries/chain/transaction_context.cpp
Labels: OCI

#358 [3.1] Curate eos.io refs and remove unused doc metadata [docs]
  docs.json
  eos.doxygen.in
  plugins/chain_api_plugin/chain.swagger.yaml
  plugins/db_size_api_plugin/db_size.swagger.yaml
  plugins/net_api_plugin/net.swagger.yaml
  plugins/producer_api_plugin/producer.swagger.yaml
  plugins/test_control_api_plugin/test_control.swagger.yaml
  plugins/trace_api_plugin/trace_api.swagger.yaml
Labels: documentation

#388 [3.2 -> main] Warning message for trx being dropped due to high traffic
  plugins/chain_api_plugin/chain.swagger.yaml
  plugins/db_size_api_plugin/db_size.swagger.yaml
  plugins/net_api_plugin/net.swagger.yaml
  plugins/net_plugin/net_plugin.cpp
  plugins/test_control_api_plugin/test_control.swagger.yaml
Labels: OCI

#389 [3.1 -> 3.2] Clear expired transactions before snapshot and integrity hash
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/controller.hpp
  unittests/snapshot_tests.cpp
Labels: OCI

#390 [3.2 -> main] Clear expired transactions before snapshot and integrity hash
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/controller.hpp
  unittests/snapshot_tests.cpp
Labels: OCI

#400 [3.1] Use error log instead of warning log when resource_monitor exceeds threshold
  plugins/resource_monitor_plugin/include/eosio/resource_monitor_plugin/file_space_handler.hpp
Labels: OCI

#401 don't triage new issues if they're already assigned to a project
  .github/workflows/label_new_issues.yaml
Labels: cicd
