Repository AntelopeIO/leap, pull requests merged in 2023-07, with the labels that each got.

#1368 [4.0] Removed "deprecated" from help for speculative read-mode
  docs/01_nodeos/03_plugins/chain_plugin/index.md
  plugins/chain_plugin/chain_plugin.cpp
Labels: OCI

#1371 [4.0 -> main] Removed "deprecated" from help for speculative read-mode
  docs/01_nodeos/03_plugins/chain_plugin/index.md
  plugins/chain_plugin/chain_plugin.cpp
Labels: OCI

#1366 [4.0] Close connection on aysnc_read with a closed socket
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#1376 [4.0 -> main] Close connection on aysnc_read with a closed socket
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#1375 [4.0] SHiP: Support snapshot start with full deltas
  plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp
  plugins/state_history_plugin/state_history_plugin.cpp
  plugins/state_history_plugin/tests/session_test.cpp
  tests/TestHarness/Cluster.py
  tests/TestHarness/testUtils.py
  tests/ship_streamer.cpp
  tests/ship_streamer_test.py
Labels: OCI

#1379 [3.2] Emit correct trace id for deferred trx before replace_deferred protocol feature activation
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/transaction_context.hpp
  libraries/chain/transaction_context.cpp
  unittests/protocol_feature_tests.cpp
Labels: OCI

#1380 [3.2 -> 4.0] Emit correct trace id for deferred trx before replace_deferred protocol feature activation
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/transaction_context.hpp
  libraries/chain/transaction_context.cpp
  unittests/protocol_feature_tests.cpp
Labels: OCI

#1384 [4.0] SHiP: Improve startup when large number of SHiP logs in retain directory
  libraries/chain/include/eosio/chain/log_catalog.hpp
Labels: OCI

#1387 [4.0] Test: Reduce load on ci/cd
  tests/nodeos_contrl_c_test.py
  tests/nodeos_startup_catchup.py
Labels: OCI

#1389 [4.0 -> main] Test: Reduce load on ci/cd
  tests/nodeos_contrl_c_test.py
  tests/nodeos_startup_catchup.py
Labels: OCI

#1388 [4.0] Test: Fix ship test to wait on correct transaction
  tests/ship_streamer_test.py
Labels: OCI

#1391 [4.0 -> main] Test: Fix ship test to wait on correct transaction
  tests/ship_streamer_test.py
Labels: OCI

#1386 Signal accepted_block after it is marked valid
  libraries/chain/controller.cpp
  unittests/chain_tests.cpp
  unittests/deep-mind/deep-mind.log
Labels: OCI

#1401 Test Fix: performance test - use 475ms for max_transaction_cpu_usage
  tests/performance_tests/genesis.json
Labels: OCI

#1400 Update max_block_cpu_usage and max_transaction_cpu_usage properly.
  tests/TestHarness/launcher.py
Labels: OCI

#1356 [PH] Create workflow to test backward compatibility of performance harness
  .github/workflows/build.yaml
  .github/workflows/build_base.yaml
  .github/workflows/ph_backward_compatibility.yaml
  tests/TestHarness/Node.py
  tests/performance_tests/performance_test_basic.py
Labels: OCI

#1408 Revert back to non-oc execution for read-only trxs
  libraries/chain/CMakeLists.txt
  libraries/chain/apply_context.cpp
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/controller.hpp
  libraries/chain/include/eosio/chain/wasm_interface.hpp
  libraries/chain/include/eosio/chain/wasm_interface_collection.hpp
  libraries/chain/include/eosio/chain/wasm_interface_private.hpp
  libraries/chain/include/eosio/chain/webassembly/runtime_interface.hpp
  libraries/chain/wasm_interface.cpp
  libraries/chain/wasm_interface_collection.cpp
  libraries/chain/webassembly/runtimes/eos-vm.cpp
  libraries/testing/tester.cpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/producer_plugin/test/CMakeLists.txt
  tests/CMakeLists.txt
  tests/read_only_trx_test.py
  tests/test_read_only_trx.cpp
  unittests/test_utils.hpp
Labels: OCI

#1438 Test Fix: libtester test failures in CICD
  .github/workflows/build.yaml
Labels: OCI, CICD

#1436 Test Fix: Change default max-transaction-cpu-usage for tests
  tests/TestHarness/launcher.py
Labels: OCI

#1444 set `DEBIAN_FRONTEND` & `TZ` globally during libtester job
  .github/workflows/build.yaml
Labels: CICD

#1411 Listen on multiple addresses for net_plugin p2p.
  plugins/net_plugin/include/eosio/net_plugin/auto_bp_peering.hpp
  plugins/net_plugin/include/eosio/net_plugin/net_plugin.hpp
  plugins/net_plugin/net_plugin.cpp
  plugins/net_plugin/tests/auto_bp_peering_unittest.cpp
  tests/CMakeLists.txt
  tests/auto_bp_peering_test.py
  tests/p2p_multiple_listen_test.py
  tests/p2p_no_listen_test.py
Labels: OCI

#1451 [4.0 -> main] Fix block time reporting log statement
  plugins/producer_plugin/producer_plugin.cpp
Labels: OCI

#1447 Do not print version and non-default args for help
  programs/nodeos/main.cpp
Labels: OCI

#1445 Upgrade to asset-artifact-download-action@v3 in CI workflows
  .github/workflows/build.yaml
  .github/workflows/ph_backward_compatibility.yaml
Labels: CICD

#1452 [3.2] Ignore http error on remote_endpoint() causing terminate
  plugins/http_plugin/include/eosio/http_plugin/beast_http_listener.hpp
Labels: OCI

#1459 Remove *.s from .gitignore
  .gitignore
Labels: OCI

#1449 [3.2] Modify trace_api_plugin to report serialization errors to user
  plugins/trace_api_plugin/test/test_data_handlers.cpp
  plugins/trace_api_plugin/test/test_responses.cpp
  plugins/trace_api_plugin/trace_api_plugin.cpp
  tests/TestHarness/testUtils.py
  tests/plugin_http_api_test.py
  tests/trace_plugin_test.py
Labels: OCI

#1468 [3.2 -> 4.0] Modify trace_api_plugin to report serialization errors to user
  plugins/trace_api_plugin/test/test_data_handlers.cpp
  plugins/trace_api_plugin/test/test_responses.cpp
  plugins/trace_api_plugin/trace_api_plugin.cpp
  tests/TestHarness/testUtils.py
  tests/plugin_http_api_test.py
  tests/trace_plugin_test.py
Labels: OCI

#1467 SHiP: Auto disable-replay-opts instead of exiting with error
  docs/01_nodeos/02_usage/01_nodeos-configuration.md
  docs/01_nodeos/03_plugins/state_history_plugin/index.md
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/controller.hpp
  libraries/state_history/include/eosio/state_history/serialization.hpp
  libraries/state_history/include/eosio/state_history/trace_converter.hpp
  libraries/state_history/trace_converter.cpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/state_history_plugin/state_history_plugin.cpp
  plugins/state_history_plugin/tests/plugin_config_test.cpp
  tests/nodeos_forked_chain_test.py
  tests/resource_monitor_plugin_test.py
  tests/ship_streamer_test.py
  tests/ship_test.py
  unittests/state_history_tests.cpp
Labels: OCI

#1469 [4.0 -> main] Modify trace_api_plugin to report serialization errors to user
  plugins/trace_api_plugin/trace_api_plugin.cpp
  tests/TestHarness/testUtils.py
  tests/plugin_http_api_test.py
  tests/trace_plugin_test.py
Labels: OCI
