Repository AntelopeIO/leap, pull requests merged in 2023-10, with the labels that each got.

#1698 Remove prometheus-exporter-address option
  plugins/prometheus_plugin/include/eosio/prometheus_plugin/prometheus_plugin.hpp
  plugins/prometheus_plugin/prometheus_plugin.cpp
Labels: OCI

#1699 Improve trx_generator http client
  plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
  tests/trx_generator/http_client_async.hpp
  tests/trx_generator/trx_provider.cpp
Labels: OCI

#1703 migrate to new `platform-cache-workflow` to manage Dockerfile caching in CI
  .cicd/platforms.json
  .github/workflows/build.yaml
  .github/workflows/build_base.yaml
  .github/workflows/performance_harness_run.yaml
  .github/workflows/ph_backward_compatibility.yaml
  .github/workflows/platforms.yaml
Labels: CICD

#1702 Reduce the number of thread hops for read-only trxs
  libraries/custom_appbase/include/eosio/chain/application.hpp
  libraries/custom_appbase/include/eosio/chain/exec_pri_queue.hpp
  libraries/custom_appbase/tests/custom_appbase_tests.cpp
  plugins/chain_api_plugin/chain_api_plugin.cpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/http_plugin/include/eosio/http_plugin/common.hpp
  plugins/producer_plugin/producer_plugin.cpp
Labels: OCI

#1709 PH: Disable p2p trx execution on validation and api nodes
  tests/PerformanceHarness/performance_test_basic.py
Labels: OCI

#1718 Fix: segfault switching between read/write windows
  libraries/custom_appbase/include/eosio/chain/exec_pri_queue.hpp
  libraries/custom_appbase/tests/custom_appbase_tests.cpp
  tests/CMakeLists.txt
  tests/read_only_trx_test.py
Labels: OCI

#1719 [4.0] Fix possible segfault switching between read/write windows
  libraries/custom_appbase/include/eosio/chain/application.hpp
  libraries/custom_appbase/include/eosio/chain/exec_pri_queue.hpp
  libraries/custom_appbase/tests/custom_appbase_tests.cpp
  plugins/producer_plugin/producer_plugin.cpp
Labels: OCI

#1728 [5.0] Test: Retry set contract on failure
  tests/CMakeLists.txt
  tests/TestHarness/transactions.py
Labels: OCI

#1737 [5.0 -> main] Test: Retry set contract on failure
  tests/CMakeLists.txt
  tests/TestHarness/transactions.py
Labels: OCI

#1733 [5.0] Improve cleos error messages
  programs/cleos/help_text.cpp.in
  programs/cleos/httpc.cpp
Labels: OCI

#1738 [5.0 -> main] Improve cleos error messages
  programs/cleos/help_text.cpp.in
  programs/cleos/httpc.cpp
Labels: OCI

#1739 [5.0] Test: Pass in exitOnError so that a retry is allowed
  tests/TestHarness/Node.py
  tests/TestHarness/queries.py
  tests/TestHarness/transactions.py
Labels: OCI

#1740 [5.0 -> main] Test: Pass in exitOnError so that a retry is allowed
  tests/TestHarness/Node.py
  tests/TestHarness/queries.py
  tests/TestHarness/transactions.py
Labels: OCI

#1741 [5.0] Support throttling block syncing to peers
  plugins/net_plugin/include/eosio/net_plugin/auto_bp_peering.hpp
  plugins/net_plugin/include/eosio/net_plugin/net_plugin.hpp
  plugins/net_plugin/include/eosio/net_plugin/protocol.hpp
  plugins/net_plugin/net_plugin.cpp
  plugins/net_plugin/tests/CMakeLists.txt
  plugins/net_plugin/tests/auto_bp_peering_unittest.cpp
  plugins/net_plugin/tests/rate_limit_parse_unittest.cpp
  plugins/prometheus_plugin/metrics.hpp
  tests/CMakeLists.txt
  tests/TestHarness/testUtils.py
  tests/block_log_util_test.py
  tests/p2p_multiple_listen_test.py
  tests/p2p_sync_throttle_test.py
  tests/p2p_sync_throttle_test_shape.json
  tests/plugin_http_api_test.py
  tools/net-util.py
Labels: OCI

#1742 [5.0 -> main] Support throttling block syncing to peers
  plugins/net_plugin/include/eosio/net_plugin/auto_bp_peering.hpp
  plugins/net_plugin/include/eosio/net_plugin/net_plugin.hpp
  plugins/net_plugin/include/eosio/net_plugin/protocol.hpp
  plugins/net_plugin/net_plugin.cpp
  plugins/net_plugin/tests/CMakeLists.txt
  plugins/net_plugin/tests/auto_bp_peering_unittest.cpp
  plugins/net_plugin/tests/rate_limit_parse_unittest.cpp
  plugins/prometheus_plugin/metrics.hpp
  tests/CMakeLists.txt
  tests/TestHarness/testUtils.py
  tests/block_log_util_test.py
  tests/p2p_multiple_listen_test.py
  tests/p2p_sync_throttle_test.py
  tests/p2p_sync_throttle_test_shape.json
  tests/plugin_http_api_test.py
  tools/net-util.py
Labels: OCI

#1745 [5.0 -> main] P2P: Modify log level for message to avoid confusion
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#1747 [5.0] Test: larger timeout of set contract
  tests/TestHarness/transactions.py
Labels: OCI

#1748 [5.0 -> main] Test: larger timeout of set contract
  tests/TestHarness/transactions.py
Labels: OCI

#1753 [5.0] fix "All Required Tests Passed" CI Branch Protection
  .github/workflows/build.yaml
Labels: CICD

#1752 [5.0] Fix compiler warning
  plugins/producer_plugin/test/test_disallow_delayed_trx.cpp
Labels: OCI

#1761 [5.0 -> main] Fix compiler warning
  plugins/producer_plugin/test/test_disallow_delayed_trx.cpp
Labels: OCI

#1750 [5.0] Prometheus: Add stable identifier for P2P connections
  plugins/net_plugin/include/eosio/net_plugin/net_plugin.hpp
  plugins/net_plugin/net_plugin.cpp
  plugins/prometheus_plugin/metrics.hpp
  tests/nodeos_run_test.py
  tests/p2p_sync_throttle_test.py
  tools/net-util.py
Labels: OCI

#1765 [5.0 -> main] Prometheus: Add stable identifier for P2P connections
  plugins/net_plugin/include/eosio/net_plugin/net_plugin.hpp
  plugins/net_plugin/net_plugin.cpp
  plugins/prometheus_plugin/metrics.hpp
  tests/nodeos_run_test.py
  tests/p2p_sync_throttle_test.py
  tools/net-util.py
Labels: OCI

#1766 [5.0] Test: read-only trxs should only be posted to read_exclusive queue
  tests/test_read_only_trx.cpp
Labels: OCI

#1767 [5.0 -> main] Test: read-only trxs should only be posted to read_exclusive queue
  tests/test_read_only_trx.cpp
Labels: OCI

#1770 [4.0] Only return wasm config settings if configurable wasm limits enabled
  plugins/chain_plugin/chain_plugin.cpp
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
  tests/chain_plugin_tests.cpp
Labels: OCI

#1773 [4.0 -> 5.0] Only return wasm config settings if configurable wasm limits enabled
  plugins/chain_plugin/chain_plugin.cpp
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
  tests/chain_plugin_tests.cpp
Labels: OCI

#1769 [4.0] Signal accepted_block after it is marked valid
  libraries/chain/controller.cpp
  unittests/chain_tests.cpp
  unittests/deep-mind/deep-mind.log
Labels: OCI

#1775 [5.0 -> main] Only return wasm config settings if configurable wasm limits enabled
  plugins/chain_plugin/chain_plugin.cpp
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
  tests/chain_plugin_tests.cpp
Labels: OCI

#1777 [4.0 -> 5.0] Signal accepted_block after it is marked valid
  unittests/chain_tests.cpp
Labels: OCI

#1787 [4.0 -> 5.0] Recreate EOS VM OC code cache if corrupt
  libraries/chain/webassembly/runtimes/eos-vm-oc/code_cache.cpp
  plugins/chain_plugin/chain_plugin.cpp
Labels: OCI

#1788 [5.0 -> main] Recreate EOS VM OC code cache if corrupt
  libraries/chain/webassembly/runtimes/eos-vm-oc/code_cache.cpp
  plugins/chain_plugin/chain_plugin.cpp
Labels: OCI

#1791 [5.0] P2P: Fix: Throttling of last block of request caused lost block
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#1793 [5.0 -> main] P2P: Fix: Throttling of last block of request caused lost block
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#1801 [4.0] SHiP: Make sure we append to index file
  libraries/state_history/include/eosio/state_history/log.hpp
Labels: OCI

#1798 [4.0 -> 5.0] SHiP: Fixes: Stack overflow, invalid index, split file access
  libraries/state_history/include/eosio/state_history/log.hpp
  plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp
  plugins/state_history_plugin/state_history_plugin.cpp
  plugins/state_history_plugin/tests/session_test.cpp
  tests/ship_streamer_test.py
Labels: OCI

#1802 [5.0 -> main] SHiP: Fixes: Stack overflow, invalid index, split file access
  libraries/state_history/include/eosio/state_history/log.hpp
  plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp
  plugins/state_history_plugin/state_history_plugin.cpp
  plugins/state_history_plugin/tests/session_test.cpp
  tests/ship_streamer_test.py
Labels: OCI

#1800 [5.0] Replaced `cpu-effort-percent` with `produce-block-offset-ms`
  docs/01_nodeos/03_plugins/producer_plugin/10_block-producing-explained.md
  docs/01_nodeos/03_plugins/producer_plugin/index.md
  libraries/chain/include/eosio/chain/config.hpp
  plugins/producer_plugin/include/eosio/producer_plugin/block_timing_util.hpp
  plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
  plugins/producer_plugin/producer_plugin.cpp
  plugins/producer_plugin/test/test_block_timing_util.cpp
  tests/PerformanceHarness/README.md
  tests/PerformanceHarness/performance_test_basic.py
  tests/p2p_high_latency_test.py
Labels: documentation, OCI

#1805 [5.0 -> main] Replaced `cpu-effort-percent` with `produce-block-offset-ms`
  docs/01_nodeos/03_plugins/producer_plugin/10_block-producing-explained.md
  docs/01_nodeos/03_plugins/producer_plugin/index.md
  libraries/chain/include/eosio/chain/config.hpp
  plugins/producer_plugin/include/eosio/producer_plugin/block_timing_util.hpp
  plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
  plugins/producer_plugin/producer_plugin.cpp
  plugins/producer_plugin/test/test_block_timing_util.cpp
  tests/PerformanceHarness/README.md
  tests/PerformanceHarness/performance_test_basic.py
  tests/p2p_high_latency_test.py
Labels: OCI

#1811 [5.0] P2P: Throttle over sync window
  plugins/net_plugin/net_plugin.cpp
  tests/p2p_sync_throttle_test.py
Labels: OCI

#1812 [5.0 -> main] P2P: Throttle over sync window
  plugins/net_plugin/net_plugin.cpp
  tests/p2p_sync_throttle_test.py
Labels: OCI

#1710 [5.0] integrate reproducible build with CI Build & Test workflow
  .github/workflows/build.yaml
  tools/reproducible.Dockerfile
Labels: CICD

#1818 [5.0] Test Fix: Avoid deadlock on app_thread
  tests/test_read_only_trx.cpp
Labels: OCI

#1820 [5.0 -> main] Test Fix: Avoid deadlock on app_thread
  tests/test_read_only_trx.cpp
Labels: OCI

#1840 [5.0] Normalize speculative & producer block intervals
  plugins/producer_plugin/producer_plugin.cpp
Labels: OCI

#1841 [5.0 -> main] Normalize speculative & producer block intervals
  plugins/producer_plugin/producer_plugin.cpp
Labels: OCI
