Repository AntelopeIO/leap, pull requests merged in 2023-11, with the labels that each got.

#1845 [5.0] Minimize abort/start block for speculative blocks
  plugins/producer_plugin/include/eosio/producer_plugin/block_timing_util.hpp
  plugins/producer_plugin/producer_plugin.cpp
  plugins/producer_plugin/test/test_block_timing_util.cpp
  tests/TestHarness/Node.py
  tests/distributed-transactions-test.py
Labels: OCI

#1847 [5.0 -> main] Minimize abort/start block for speculative blocks
  plugins/producer_plugin/include/eosio/producer_plugin/block_timing_util.hpp
  plugins/producer_plugin/producer_plugin.cpp
  plugins/producer_plugin/test/test_block_timing_util.cpp
  tests/TestHarness/Node.py
  tests/distributed-transactions-test.py
Labels: OCI

#1850 upload core dumps from failed tests in CI
  .github/actions/parallel-ctest-containers/action.yml
  .github/workflows/build.yaml
  .github/workflows/build_base.yaml
  .github/workflows/ph_backward_compatibility.yaml
Labels: CICD

#1814 [5.0] PH: Reliability improvements
  tests/PerformanceHarness/log_reader.py
  tests/PerformanceHarness/performance_test_basic.py
  tests/TestHarness/Cluster.py
  tests/TestHarness/Node.py
  tests/trx_generator/trx_provider.cpp
  tests/trx_generator/trx_provider.hpp
Labels: OCI

#1853 [5.0] backport: upload core dumps from failed tests in CI
  .github/actions/parallel-ctest-containers/action.yml
  .github/workflows/build.yaml
  .github/workflows/build_base.yaml
  .github/workflows/ph_backward_compatibility.yaml
  CMakeLists.txt
  tests/CMakeLists.txt
  unittests/CMakeLists.txt
  unittests/wasm-spec-tests/generated-tests/CMakeLists.txt
Labels: CICD

#1852 [5.0 -> main] PH: Reliability improvements
  tests/PerformanceHarness/log_reader.py
  tests/PerformanceHarness/performance_test_basic.py
  tests/TestHarness/Cluster.py
  tests/TestHarness/Node.py
  tests/trx_generator/trx_provider.cpp
  tests/trx_generator/trx_provider.hpp
Labels: OCI

#1846 [5.0] Recover keys in chain thread pool
  plugins/producer_plugin/producer_plugin.cpp
Labels: OCI

#1864 [5.0 -> main] Recover keys in chain thread pool
  plugins/producer_plugin/producer_plugin.cpp
Labels: OCI

#1859 Remove thread hop to producer thread for trx signature recovery
  docs/01_nodeos/03_plugins/producer_plugin/index.md
  libraries/chain/include/eosio/chain/transaction_metadata.hpp
  libraries/chain/transaction_metadata.cpp
  plugins/producer_plugin/producer_plugin.cpp
  tests/PerformanceHarness/README.md
  tests/PerformanceHarness/performance_test.py
  tests/PerformanceHarness/performance_test_basic.py
  tests/PerformanceHarnessScenarioRunner.py
  tests/p2p_high_latency_test.py
Labels: OCI

#1867 [5.0] fix release workflow's artifact download to `wait-for-exact-target` not `wait-for-exact-target-workflow`
  .github/workflows/release.yaml
Labels: CICD

#1866 [5.0] PH: Improve error handling and use one strand
  tests/trx_generator/http_client_async.hpp
  tests/trx_generator/trx_provider.cpp
  tests/trx_generator/trx_provider.hpp
Labels: OCI

#1873 [5.0 -> main] PH: Improve error handling and use one strand
  tests/trx_generator/http_client_async.hpp
  tests/trx_generator/trx_provider.cpp
  tests/trx_generator/trx_provider.hpp
Labels: OCI

#1879 [5.0] Prometheus: Ensure valid unique_conn_node_id
  plugins/net_plugin/net_plugin.cpp
  tests/p2p_sync_throttle_test.py
Labels: OCI

#1880 [5.0 -> main] Prometheus: Ensure valid unique_conn_node_id
  plugins/net_plugin/net_plugin.cpp
  tests/p2p_sync_throttle_test.py
Labels: OCI

#1887 [5.0] Add additional tests for mapped_private
  tests/db_modes_test.sh
Labels: OCI

#1890 [5.0 -> main] Add additional tests for mapped_private
  tests/db_modes_test.sh
Labels: OCI

#1886 [5.0] Revert "Fix base64 encoding"
  libraries/libfc/include/fc/crypto/base64.hpp
  libraries/libfc/src/crypto/base64.cpp
  libraries/libfc/src/variant.cpp
  libraries/libfc/test/test_base64.cpp
  libraries/libfc/test/variant/test_variant.cpp
Labels: OCI

#1889 [3.2] Do not require trailing `=` for base64 encoded strings
  libraries/libfc/src/variant.cpp
Labels: OCI

#1891 [5.0 -> main] Revert "Fix base64 encoding"
  libraries/libfc/include/fc/crypto/base64.hpp
  libraries/libfc/src/crypto/base64.cpp
  libraries/libfc/src/variant.cpp
  libraries/libfc/test/test_base64.cpp
  libraries/libfc/test/variant/test_variant.cpp
Labels: OCI

#1888 [5.0] Fix base64 encoding - take 2
  libraries/chain/include/eosio/chain/database_utils.hpp
  libraries/libfc/include/fc/crypto/base64.hpp
  libraries/libfc/src/crypto/base64.cpp
  libraries/libfc/src/crypto/bigint.cpp
  libraries/libfc/src/crypto/elliptic_webauthn.cpp
  libraries/libfc/src/variant.cpp
  libraries/libfc/test/test_base64.cpp
  libraries/libfc/test/variant/test_variant.cpp
  tests/nodeos_run_test.py
Labels: OCI

#1892 [3.2 -> 4.0] Do not require trailing `=` for base64 encoded strings
  libraries/libfc/src/variant.cpp
Labels: OCI

#1893 [5.0 -> main] Fix base64 encoding - take 2
  libraries/chain/include/eosio/chain/database_utils.hpp
  libraries/libfc/include/fc/crypto/base64.hpp
  libraries/libfc/src/crypto/base64.cpp
  libraries/libfc/src/crypto/bigint.cpp
  libraries/libfc/src/crypto/elliptic_webauthn.cpp
  libraries/libfc/src/variant.cpp
  libraries/libfc/test/test_base64.cpp
  libraries/libfc/test/variant/test_variant.cpp
  tests/nodeos_run_test.py
Labels: OCI

#1898 [5.0 -> main] Benchmark BLS host functions, Do not require trailing = for base64 encoded strings
  benchmark/CMakeLists.txt
  benchmark/alt_bn_128.cpp
  benchmark/benchmark.cpp
  benchmark/benchmark.hpp
  benchmark/blake2.cpp
  benchmark/bls.cpp
  benchmark/hash.cpp
  benchmark/key.cpp
  benchmark/main.cpp
  benchmark/modexp.cpp
  libraries/chain/include/eosio/chain/transaction_context.hpp
Labels: OCI

#1906 [5.0 -> main] Change remaining references of mandel to leap
  docs/00_install/01_build-from-source/00_build-unsupported-os.md
  docs/index.md
  docs/leap_components.png
  libraries/chain/include/eosio/chain/kv_config.hpp
Labels: OCI

#1905 [5.0] Test: net_plugin test cleanup
  plugins/net_plugin/include/eosio/net_plugin/auto_bp_peering.hpp
  plugins/net_plugin/include/eosio/net_plugin/net_utils.hpp
  plugins/net_plugin/net_plugin.cpp
  plugins/net_plugin/tests/CMakeLists.txt
  plugins/net_plugin/tests/auto_bp_peering_unittest.cpp
  plugins/net_plugin/tests/main.cpp
  plugins/net_plugin/tests/rate_limit_parse_unittest.cpp
Labels: OCI

#1921 IF: Update bios contract to have `setfinset` which calls host `set_finalizers`
  libraries/chain/controller.cpp
  libraries/chain/webassembly/privileged.cpp
  libraries/libfc/test/test_bls.cpp
  libraries/testing/contracts/eosio.bios/eosio.bios.abi
  libraries/testing/contracts/eosio.bios/eosio.bios.cpp
  libraries/testing/contracts/eosio.bios/eosio.bios.hpp
  libraries/testing/contracts/eosio.bios/eosio.bios.wasm
  libraries/testing/include/eosio/testing/tester.hpp
  libraries/testing/tester.cpp
  unittests/api_tests.cpp
  unittests/deep-mind/deep-mind.log
  unittests/test_utils.hpp
Labels: OCI

#1926 IF: Refactor chain_pacemaker ownership
  CMakeModules/EosioTester.cmake.in
  CMakeModules/EosioTesterBuild.cmake.in
  libraries/chain/CMakeLists.txt
  libraries/chain/block_header_state.cpp
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/controller.hpp
  libraries/chain/webassembly/privileged.cpp
  libraries/hotstuff/CMakeLists.txt
  libraries/hotstuff/chain_pacemaker.cpp
  libraries/hotstuff/include/eosio/hotstuff/base_pacemaker.hpp
  libraries/hotstuff/include/eosio/hotstuff/chain_pacemaker.hpp
  libraries/hotstuff/include/eosio/hotstuff/hotstuff.hpp
  libraries/hotstuff/include/eosio/hotstuff/qc_chain.hpp
  libraries/hotstuff/include/eosio/hotstuff/state.hpp
  libraries/hotstuff/include/eosio/hotstuff/test_pacemaker.hpp
  libraries/hotstuff/qc_chain.cpp
  libraries/hotstuff/test/test_hotstuff.cpp
  libraries/hotstuff/test/test_pacemaker.cpp
  libraries/testing/CMakeLists.txt
  libraries/testing/include/eosio/testing/tester.hpp
  libraries/testing/tester.cpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
  plugins/net_plugin/include/eosio/net_plugin/protocol.hpp
  plugins/net_plugin/net_plugin.cpp
  plugins/producer_plugin/producer_plugin.cpp
  tests/chain_plugin_tests.cpp
  tests/get_producers_tests.cpp
  tests/get_table_seckey_tests.cpp
  tests/get_table_tests.cpp
  tests/test_chain_plugin.cpp
  unittests/api_tests.cpp
  unittests/producer_schedule_hs_tests.cpp
Labels: OCI

#1933 IF: Fix set_finalizers fthreshold check
  libraries/chain/webassembly/privileged.cpp
  libraries/testing/tester.cpp
  unittests/api_tests.cpp
Labels: OCI

#898 add some hints on how to use bash-complete in README
  README.md
Labels: documentation

#1041 Table of Contents proposal
  README.md
Labels: documentation
