Repository AntelopeIO/leap, pull requests merged in 2023-08, with the labels that each got.

#1378 [PH] Create workflow for manually dispatching performance harness runs
  .github/workflows/build.yaml
  .github/workflows/build_base.yaml
  .github/workflows/performance_harness_run.yaml
  .github/workflows/ph_backward_compatibility.yaml
  .github/workflows/platforms.yaml
Labels: OCI

#1476 Tests: Add back old commented out unittests
  unittests/api_tests.cpp
  unittests/producer_schedule_tests.cpp
  unittests/resource_limits_test.cpp
  unittests/wasm_tests.cpp
Labels: OCI

#1132 check for existance of BMI2 & ADX instructions on CI workers
  .github/workflows/build.yaml
Labels: CICD

#1489 Require dry-run trxs to have authorization and add tests
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/apply_context.hpp
  libraries/chain/include/eosio/chain/controller.hpp
  libraries/chain/transaction_context.cpp
  libraries/chain/webassembly/authorization.cpp
  libraries/chain/webassembly/crypto.cpp
  libraries/chain/webassembly/permission.cpp
  libraries/chain/webassembly/privileged.cpp
  libraries/chain/webassembly/runtimes/eos-vm.cpp
  unittests/delay_tests.cpp
  unittests/dry_run_trx_tests.cpp
Labels: documentation, OCI

#1481 Smarter block deadlines for speculative blocks
  plugins/producer_plugin/include/eosio/producer_plugin/block_timing_util.hpp
  plugins/producer_plugin/producer_plugin.cpp
  plugins/producer_plugin/test/test_block_timing_util.cpp
Labels: OCI

#1477 Add per peer prometheus metrics and a TUI to view them.
  plugins/chain_plugin/chain_plugin.cpp
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
  plugins/net_plugin/include/eosio/net_plugin/net_plugin.hpp
  plugins/net_plugin/net_plugin.cpp
  plugins/prometheus_plugin/include/eosio/prometheus_plugin/prometheus_plugin.hpp
  plugins/prometheus_plugin/metrics.hpp
  plugins/prometheus_plugin/prometheus_plugin.cpp
  tests/cluster_launcher.py
  tests/plugin_http_api_test.py
  tools/CMakeLists.txt
  tools/net-util.py
Labels: OCI

#1502 Prometheus: Add speculative block metrics
  plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
  plugins/producer_plugin/producer_plugin.cpp
  plugins/prometheus_plugin/metrics.hpp
Labels: OCI

#1534 IF: Fix deep-mind tests
  libraries/libfc/test/test_bls.cpp
  unittests/deep-mind/deep-mind.log
Labels: OCI

#1535 Create performance harness module
  .github/workflows/performance_harness_run.yaml
  tests/CMakeLists.txt
  tests/PerformanceHarness/CMakeLists.txt
  tests/PerformanceHarness/NodeosPluginArgs/BasePluginArgs.py
  tests/PerformanceHarness/NodeosPluginArgs/CMakeLists.txt
  tests/PerformanceHarness/NodeosPluginArgs/__init__.py
  tests/PerformanceHarness/NodeosPluginArgs/generate_nodeos_plugin_args_class_files.py
  tests/PerformanceHarness/README.md
  tests/PerformanceHarness/__init__.py
  tests/PerformanceHarness/cpuTrxData.json
  tests/PerformanceHarness/genesis.json
  tests/PerformanceHarness/log_reader.py
  tests/PerformanceHarness/performance_test.py
  tests/PerformanceHarness/performance_test_basic.py
  tests/PerformanceHarness/ph_op_modes.md
  tests/PerformanceHarness/ramTrxData.json
  tests/PerformanceHarness/readOnlyTrxData.json
  tests/PerformanceHarness/userTrxDataNewAccount.json
  tests/PerformanceHarness/userTrxDataTransfer.json
  tests/PerformanceHarnessScenarioRunner.py
  tests/performance_tests/CMakeLists.txt
Labels: OCI

#1559 IF: Remove controller emit of hotstuff messages
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/controller.hpp
  libraries/chain/include/eosio/chain/hotstuff.hpp
  libraries/hotstuff/chain_pacemaker.cpp
  libraries/hotstuff/include/eosio/hotstuff/chain_pacemaker.hpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
  plugins/net_plugin/include/eosio/net_plugin/net_plugin.hpp
  plugins/net_plugin/include/eosio/net_plugin/protocol.hpp
  plugins/net_plugin/net_plugin.cpp
  plugins/producer_plugin/include/eosio/producer_plugin/qc_chain.hpp.bkp
Labels: OCI

#1560 IF: Support larger number of finalizers
  libraries/chain/include/eosio/chain/hotstuff.hpp
  libraries/hotstuff/include/eosio/hotstuff/qc_chain.hpp
  libraries/hotstuff/qc_chain.cpp
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
Labels: OCI

#1566 IF: Remove NULL_BLOCK_ID & NULL_PROPOSAL_ID and use empty()
  libraries/chain/include/eosio/chain/hotstuff.hpp
  libraries/hotstuff/include/eosio/hotstuff/qc_chain.hpp
  libraries/hotstuff/qc_chain.cpp
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
Labels: OCI

#1563 Remove some conversion operators
  libraries/chain/authority.cpp
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/authority.hpp
  libraries/chain/include/eosio/chain/producer_schedule.hpp
  libraries/libfc/include/fc/crypto/private_key.hpp
  libraries/libfc/include/fc/crypto/public_key.hpp
  libraries/libfc/src/crypto/private_key.cpp
  libraries/libfc/src/crypto/public_key.cpp
  libraries/libfc/test/crypto/test_cypher_suites.cpp
  libraries/state_history/include/eosio/state_history/serialization.hpp
  plugins/chain_plugin/account_query_db.cpp
  plugins/producer_plugin/producer_plugin.cpp
  plugins/wallet_plugin/wallet.cpp
  plugins/wallet_plugin/wallet_manager.cpp
  programs/cleos/main.cpp
  tests/trx_generator/trx_generator.hpp
  tests/wallet_tests.cpp
  unittests/abi_tests.cpp
  unittests/auth_tests.cpp
  unittests/misc_tests.cpp
  unittests/state_history_tests.cpp
Labels: OCI

#1579 Make transaction generator a configurable option to TransactionGeneratorsLauncher.
  tests/PerformanceHarness/README.md
  tests/PerformanceHarness/performance_test.py
  tests/PerformanceHarness/performance_test_basic.py
  tests/PerformanceHarnessScenarioRunner.py
  tests/TestHarness/CMakeLists.txt
  tests/TestHarness/Cluster.py
  tests/TestHarness/TransactionGeneratorsLauncher.py
  tests/TestHarness/__init__.py
Labels: OCI
