Repository AntelopeIO/leap, pull requests merged in 2023-04, with the labels that each got.

#944 [4.0 -> main] forkdb reset in replay since blocks are signaled
  libraries/chain/controller.cpp
Labels: OCI

#943 [3.2] SHiP Fix forking behavior
  plugins/state_history_plugin/state_history_plugin.cpp
  tests/CMakeLists.txt
  tests/ship_client.cpp
  tests/ship_streamer.cpp
  tests/ship_streamer_test.py
  tests/ship_test.py
Labels: OCI

#952 [3.2 -> 4.0] SHiP Fix forking behavior
  plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp
  tests/CMakeLists.txt
  tests/ship_client.cpp
  tests/ship_streamer.cpp
  tests/ship_streamer_test.py
  tests/ship_test.py
Labels: OCI

#955 [4.0 -> main] SHiP Fix forking behavior
  plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp
  tests/CMakeLists.txt
  tests/ship_client.cpp
  tests/ship_streamer.cpp
  tests/ship_streamer_test.py
  tests/ship_test.py
Labels: OCI

#912 Return 400 http error for unknown account
  plugins/chain_plugin/chain_plugin.cpp
  plugins/http_plugin/http_plugin.cpp
  tests/plugin_http_api_test.py
Labels: documentation, OCI

#945 [PH] Reduce log Usage and Other Performance Harness Improvements
  tests/performance_tests/CMakeLists.txt
  tests/performance_tests/block_trx_data_log_2_0_14.txt.gz
  tests/performance_tests/log_reader.py
  tests/performance_tests/log_reader_tests.py
  tests/performance_tests/nodeos_log_2_0_14.txt.gz
  tests/performance_tests/nodeos_log_3_2.txt.gz
  tests/performance_tests/performance_test.py
  tests/performance_tests/performance_test_basic.py
Labels: OCI

#972 [4.0] fix cpack error message
  CMakeLists.txt
  scripts/CMakeLists.txt
  scripts/install_testharness_symlinks.cmake
Labels: OCI

#983 [4.0 -> main] Set an upper limit on read-only-threads of 8
  plugins/producer_plugin/producer_plugin.cpp
  plugins/producer_plugin/test/test_read_only_trx.cpp
Labels: OCI

#939 [4.0] prometheus on different port
  plugins/http_plugin/http_plugin.cpp
  plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp
  plugins/prometheus_plugin/include/eosio/prometheus_plugin/simple_rest_server.hpp
  plugins/prometheus_plugin/prometheus_plugin.cpp
  tests/TestHarness/queries.py
  tests/plugin_http_api_test.py
Labels: OCI

#989 [4.0->main] prometheus on different port
  plugins/http_plugin/http_plugin.cpp
  plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp
  plugins/prometheus_plugin/include/eosio/prometheus_plugin/simple_rest_server.hpp
  plugins/prometheus_plugin/prometheus_plugin.cpp
  tests/TestHarness/queries.py
  tests/plugin_http_api_test.py
Labels: OCI

#986 [4.0] Restore read-mode=speculative
  docs/01_nodeos/03_plugins/chain_plugin/index.md
  docs/01_nodeos/07_concepts/05_storage-and-read-modes.md
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/controller.hpp
  plugins/chain_plugin/chain_plugin.cpp
  tests/CMakeLists.txt
  tests/distributed-transactions-test.py
  tests/nodeos_irreversible_mode_test.py
  tests/nodeos_read_terminate_at_block_test.py
Labels: OCI

#990 Update boost version.
  CMakeLists.txt
  README.md
  libraries/libfc/include/fc/log/appender.hpp
  libraries/libfc/test/network/test_message_buffer.cpp
  plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
  plugins/state_history_plugin/state_history_plugin.cpp
  tests/ship_client.cpp
Labels: OCI

#992 [4.0 -> main] Restore read-mode=speculative
  docs/01_nodeos/03_plugins/chain_plugin/index.md
  docs/01_nodeos/07_concepts/05_storage-and-read-modes.md
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/controller.hpp
  plugins/chain_plugin/chain_plugin.cpp
  tests/CMakeLists.txt
  tests/distributed-transactions-test.py
  tests/nodeos_irreversible_mode_test.py
  tests/nodeos_read_terminate_at_block_test.py
Labels: OCI

#1005 [4.0] fix resource not found bug
  plugins/prometheus_plugin/include/eosio/prometheus_plugin/simple_rest_server.hpp
  tests/TestHarness/queries.py
  tests/plugin_http_api_test.py
Labels: OCI

#996 [3.2] response to disallowed host
  plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
  tests/http_plugin_test.py
Labels: OCI

#1006 [4.0->main] prometheus fix main
  plugins/prometheus_plugin/include/eosio/prometheus_plugin/simple_rest_server.hpp
  tests/TestHarness/queries.py
  tests/plugin_http_api_test.py
Labels: OCI

#1000 [3.2] Log all http request/response at debug log level
  plugins/http_plugin/http_plugin.cpp
  plugins/http_plugin/include/eosio/http_plugin/beast_http_listener.hpp
  plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
Labels: OCI

#1008 [3.2->4.0] response to disallowed host
  plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
  tests/http_plugin_test.py
Labels: OCI

#1009 [3.2 -> 4.0] Log all http request/response at debug log level
  plugins/http_plugin/http_plugin.cpp
  plugins/http_plugin/include/eosio/http_plugin/beast_http_listener.hpp
  plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
Labels: OCI

#867 Optimize block start time
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/config.hpp
  libraries/chain/include/eosio/chain/controller.hpp
  plugins/producer_plugin/include/eosio/producer_plugin/block_timing_util.hpp
  plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
  plugins/producer_plugin/producer_plugin.cpp
  plugins/producer_plugin/test/CMakeLists.txt
  plugins/producer_plugin/test/test_block_timing_util.cpp
  tests/performance_tests/README.md
  tests/performance_tests/performance_test.py
  tests/performance_tests/performance_test_basic.py
  tests/plugin_http_api_test.py
Labels: documentation, OCI

#1015 [4.0 -> main] Log all http request/response at debug log level
  plugins/http_plugin/http_plugin.cpp
  plugins/http_plugin/include/eosio/http_plugin/beast_http_listener.hpp
  plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
Labels: OCI

#1017 [3.2 -> 4.0] Reduce producer_plugin debug level log spam
  plugins/producer_plugin/include/eosio/producer_plugin/subjective_billing.hpp
Labels: OCI

#1019 [4.0 -> main] Reduce producer_plugin debug level log spam
  plugins/producer_plugin/include/eosio/producer_plugin/subjective_billing.hpp
Labels: OCI

#1022 P2P: clang-tidy fixes
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#994 Small but measurable improvement to executor queue
  libraries/custom_appbase/include/eosio/chain/application.hpp
Labels: OCI

#958 Test: Add SHiP forking and have_positions unittest
  libraries/state_history/include/eosio/state_history/types.hpp
  plugins/state_history_plugin/state_history_plugin.cpp
  plugins/state_history_plugin/tests/session_test.cpp
Labels: OCI

#967 [PH] block producer op mode
  tests/TestHarness/TestHelper.py
  tests/performance_tests/CMakeLists.txt
  tests/performance_tests/README.md
  tests/performance_tests/performance_test.py
  tests/performance_tests/performance_test_basic.py
  tests/performance_tests/ph_op_modes.md
Labels: OCI

#1040 P2P: Misc improvements
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#1045 P2P: Save and retry unlinkable blocks
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#1039 mitigate unix socket path problem
  plugins/http_plugin/http_plugin.cpp
Labels: OCI

#1056 [PH] Update initial API Node Op Mode documentation.
  tests/performance_tests/ph_op_modes.md
Labels: OCI

#1052 [PH] Add http client async
  tests/performance_tests/ph_op_modes.md
  tests/trx_generator/CMakeLists.txt
  tests/trx_generator/http_client_async.hpp
  tests/trx_generator/simple_rest_server.hpp
  tests/trx_generator/trx_generator_tests.cpp
Labels: OCI

#1054 Move abi serialization of transaction trace off main thread for `chain_plugin: get_table_rows` and `get_account`
  plugins/chain_api_plugin/chain_api_plugin.cpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
  plugins/http_plugin/include/eosio/http_plugin/macros.hpp
  tests/chain_plugin_tests.cpp
  tests/get_table_seckey_tests.cpp
  tests/get_table_tests.cpp
  tests/test_chain_plugin.cpp
Labels: enhancement

#1076 Refactor: Move subjective_billing to chain library
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/controller.hpp
  libraries/chain/include/eosio/chain/subjective_billing.hpp
  plugins/chain_plugin/CMakeLists.txt
  plugins/chain_plugin/chain_plugin.cpp
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
  plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
  plugins/producer_plugin/producer_plugin.cpp
  plugins/producer_plugin/test/CMakeLists.txt
  tests/CMakeLists.txt
  tests/chain_plugin_tests.cpp
  tests/get_producers_tests.cpp
  tests/get_table_seckey_tests.cpp
  tests/get_table_tests.cpp
  tests/test_chain_plugin.cpp
  unittests/subjective_billing_tests.cpp
Labels: OCI

#1093 [PH] Initial API Node (HTTP Node) Support - Topology definition/configuration
  tests/performance_tests/CMakeLists.txt
  tests/performance_tests/README.md
  tests/performance_tests/performance_test.py
  tests/performance_tests/performance_test_basic.py
  tests/performance_tests/ph_op_modes.md
Labels: OCI

#1097 fix parallel-ctest-containers creation of log tarballs on failure
  .github/actions/parallel-ctest-containers/dist/index.mjs
  .github/actions/parallel-ctest-containers/main.mjs
Labels: CICD

#1095 Refactor libfc tests into one executable
  libraries/libfc/test/CMakeLists.txt
  libraries/libfc/test/crypto/CMakeLists.txt
  libraries/libfc/test/crypto/test_blake2.cpp
  libraries/libfc/test/crypto/test_cypher_suites.cpp
  libraries/libfc/test/crypto/test_hash_functions.cpp
  libraries/libfc/test/crypto/test_k1_recover.cpp
  libraries/libfc/test/crypto/test_modular_arithmetic.cpp
  libraries/libfc/test/crypto/test_utils.hpp
  libraries/libfc/test/crypto/test_webauthn.cpp
  libraries/libfc/test/io/CMakeLists.txt
  libraries/libfc/test/io/test_cfile.cpp
  libraries/libfc/test/io/test_json.cpp
  libraries/libfc/test/io/test_tracked_storage.cpp
  libraries/libfc/test/main.cpp
  libraries/libfc/test/network/CMakeLists.txt
  libraries/libfc/test/network/test_message_buffer.cpp
  libraries/libfc/test/scoped_exit/CMakeLists.txt
  libraries/libfc/test/scoped_exit/test_scoped_exit.cpp
  libraries/libfc/test/static_variant/CMakeLists.txt
  libraries/libfc/test/static_variant/test_static_variant.cpp
  libraries/libfc/test/test_base64.cpp
  libraries/libfc/test/variant/CMakeLists.txt
  libraries/libfc/test/variant/test_variant.cpp
  libraries/libfc/test/variant_estimated_size/CMakeLists.txt
  libraries/libfc/test/variant_estimated_size/test_variant_estimated_size.cpp
Labels: OCI

#1108 Optimization: New escape_str function for sanitizing strings
  libraries/chain/apply_context.cpp
  libraries/libfc/include/fc/string.hpp
  libraries/libfc/src/string.cpp
  libraries/libfc/test/CMakeLists.txt
  libraries/libfc/test/test_escape_str.cpp
  plugins/producer_plugin/producer_plugin.cpp
Labels: OCI
