Repository AntelopeIO/leap, pull requests merged in 2023-03, with the labels that each got.

#737 [3.2] SHiP do not truncate logs when starting from genesis
  libraries/state_history/include/eosio/state_history/log.hpp
  tests/ship_log.cpp
  unittests/restart_chain_tests.cpp
Labels: OCI

#758 move gelf logging to another thread
  libraries/libfc/include/fc/log/appender.hpp
  libraries/libfc/include/fc/log/console_appender.hpp
  libraries/libfc/include/fc/log/dmlog_appender.hpp
  libraries/libfc/include/fc/log/gelf_appender.hpp
  libraries/libfc/include/fc/log/logger_config.hpp
  libraries/libfc/src/log/dmlog_appender.cpp
  libraries/libfc/src/log/gelf_appender.cpp
  libraries/libfc/src/log/logger_config.cpp
  programs/keosd/main.cpp
  programs/nodeos/main.cpp
Labels: OCI

#628 Merge SHiP stability fixes & log splitting & memory usage improvements
  libraries/chain/include/eosio/chain/log_catalog.hpp
  libraries/chain/include/eosio/chain/log_data_base.hpp
  libraries/libfc/include/fc/io/datastream.hpp
  libraries/state_history/compression.cpp
  libraries/state_history/create_deltas.cpp
  libraries/state_history/include/eosio/state_history/compression.hpp
  libraries/state_history/include/eosio/state_history/create_deltas.hpp
  libraries/state_history/include/eosio/state_history/log.hpp
  libraries/state_history/include/eosio/state_history/serialization.hpp
  libraries/state_history/include/eosio/state_history/trace_converter.hpp
  libraries/state_history/include/eosio/state_history/types.hpp
  libraries/state_history/trace_converter.cpp
  libraries/testing/include/eosio/testing/tester.hpp
  libraries/testing/tester.cpp
  plugins/state_history_plugin/CMakeLists.txt
  plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp
  plugins/state_history_plugin/state_history_plugin.cpp
  plugins/state_history_plugin/tests/CMakeLists.txt
  plugins/state_history_plugin/tests/session_test.cpp
  tests/CMakeLists.txt
  tests/ship_log.cpp
  tests/ship_streamer.cpp
  unittests/state_history_tests.cpp
Labels: documentation, OCI

#727 SHiP move client handling off the main thread
  libraries/chain/block_log.cpp
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/block_log.hpp
  libraries/chain/include/eosio/chain/chain_id_type.hpp
  libraries/chain/include/eosio/chain/controller.hpp
  libraries/libfc/include/fc/crypto/sha256.hpp
  libraries/state_history/include/eosio/state_history/log.hpp
  plugins/net_plugin/net_plugin.cpp
  plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp
  plugins/state_history_plugin/state_history_plugin.cpp
  plugins/state_history_plugin/tests/session_test.cpp
  tests/CMakeLists.txt
Labels: OCI

#764 [3.2 -> main] SHiP do not truncate logs when starting from genesis
  libraries/state_history/include/eosio/state_history/log.hpp
  tests/ship_log.cpp
  unittests/restart_chain_tests.cpp
Labels: OCI

#745 Remove HTTPS support from nodeos & keosd
  docs/01_nodeos/03_plugins/http_client_plugin/index.md
  docs/01_nodeos/03_plugins/http_plugin/index.md
  docs/01_nodeos/03_plugins/index.md
  docs/03_keosd/10_usage.md
  libraries/libfc/CMakeLists.txt
  libraries/libfc/src/network/http/http_client.cpp
  plugins/http_client_plugin/http_client_plugin.cpp
  plugins/http_plugin/http_plugin.cpp
  plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
  plugins/http_plugin/include/eosio/http_plugin/common.hpp
  programs/cleos/main.cpp
Labels: documentation

#770 Test: Add a test that verifies restart from genesis not allowed
  plugins/state_history_plugin/tests/session_test.cpp
Labels: OCI

#773 [3.1] Move subjective bill log to `all` level of `producer_plugin` logger.
  plugins/producer_plugin/producer_plugin.cpp
Labels: OCI

#774 Fix issue with reported fork head vs retrieval of block from fork db
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/controller.hpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/net_plugin/net_plugin.cpp
  unittests/fork_test_utilities.cpp
  unittests/forked_tests.cpp
  unittests/state_history_tests.cpp
Labels: OCI

#779 [3.1 -> 3.2] Move subjective bill log to `all` level of `producer_plugin` logger.
  libraries/libfc/include/fc/log/logger.hpp
  plugins/producer_plugin/producer_plugin.cpp
Labels: OCI

#744 Add auto bp peering functionality
  libraries/chain/include/eosio/chain/producer_schedule.hpp
  plugins/net_plugin/CMakeLists.txt
  plugins/net_plugin/include/eosio/net_plugin/auto_bp_peering.hpp
  plugins/net_plugin/include/eosio/net_plugin/net_plugin.hpp
  plugins/net_plugin/net_plugin.cpp
  plugins/net_plugin/tests/CMakeLists.txt
  plugins/net_plugin/tests/auto_bp_peering_unittest.cpp
  plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
  plugins/producer_plugin/producer_plugin.cpp
  testnet.template
  tests/CMakeLists.txt
  tests/auto_bp_peering_test.py
  tests/auto_bp_peering_test_shape.json
Labels: documentation, OCI

#738 http_plugin: add support for `Expect: 100-Continue' header.
  plugins/chain_api_plugin/chain_api_plugin.cpp
  plugins/db_size_api_plugin/db_size_api_plugin.cpp
  plugins/http_plugin/CMakeLists.txt
  plugins/http_plugin/http_plugin.cpp
  plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
  plugins/http_plugin/include/eosio/http_plugin/common.hpp
  plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp
  plugins/http_plugin/tests/CMakeLists.txt
  plugins/http_plugin/tests/unit_tests.cpp
  plugins/net_api_plugin/net_api_plugin.cpp
  plugins/producer_api_plugin/producer_api_plugin.cpp
  plugins/test_control_api_plugin/test_control_api_plugin.cpp
  plugins/wallet_api_plugin/wallet_api_plugin.cpp
Labels: documentation

#781 [3.2 -> main] Move subjective bill log to `all` level of `producer_plugin` logger.
  libraries/libfc/include/fc/log/logger.hpp
  plugins/producer_plugin/producer_plugin.cpp
Labels: OCI

#777 [3.1] subjective-account-max-failures-window-size
  plugins/producer_plugin/producer_plugin.cpp
Labels: documentation, OCI

#784 Minor cleanup and fix for clang warning
  plugins/http_plugin/tests/unit_tests.cpp
Labels: OCI

#785 [3.1 -> 3.2] subjective-account-max-failures-window-size
  plugins/producer_plugin/producer_plugin.cpp
Labels: OCI

#793 [3.2 -> main] subjective-account-max-failures-window-size
  plugins/producer_plugin/producer_plugin.cpp
Labels: OCI

#797 Remove deprecated `/v1/chain/abi_bin_to_json` and `/v1/chain/abi_json_to_bin`
  plugins/chain_api_plugin/chain.swagger.yaml
  plugins/chain_api_plugin/chain_api_plugin.cpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
  programs/cleos/help_text.cpp.in
  programs/cleos/httpc.hpp
  tests/plugin_http_api_test.py
  unittests/abi_tests.cpp
Labels: documentation, OCI

#473 [PH] Feature performance harness stage 2 development
  tests/TestHarness/Cluster.py
  tests/TestHarness/Node.py
  tests/TestHarness/TestHelper.py
  tests/TestHarness/__init__.py
  tests/TestHarness/launch_transaction_generators.py
  tests/TestHarness/testUtils.py
  tests/performance_tests/CMakeLists.txt
  tests/performance_tests/NodeosPluginArgs/BasePluginArgs.py
  tests/performance_tests/NodeosPluginArgs/CMakeLists.txt
  tests/performance_tests/NodeosPluginArgs/__init__.py
  tests/performance_tests/NodeosPluginArgs/generate_nodeos_plugin_args_class_files.py
  tests/performance_tests/README.md
  tests/performance_tests/block_trx_data_log_2_0_14.txt.gz
  tests/performance_tests/cpuTrxData.json
  tests/performance_tests/log_reader.py
  tests/performance_tests/log_reader_tests.py
  tests/performance_tests/performance_test.py
  tests/performance_tests/performance_test_basic.py
  tests/performance_tests/ramTrxData.json
  tests/performance_tests/read_log_data.py
  tests/performance_tests/userTrxDataNewAccount.json
  tests/performance_tests/userTrxDataTransfer.json
  tests/trx_generator/README.md
  tests/trx_generator/main.cpp
  tests/trx_generator/trx_generator.cpp
  tests/trx_generator/trx_generator.hpp
  tests/trx_generator/trx_generator_tests.cpp
  tests/trx_generator/trx_provider.cpp
  tests/trx_generator/trx_provider.hpp
  unittests/contracts/CMakeLists.txt
  unittests/contracts/eosio.mechanics/CMakeLists.txt
  unittests/contracts/eosio.mechanics/LICENSE
  unittests/contracts/eosio.mechanics/README.md
  unittests/contracts/eosio.mechanics/eosmechanics.abi
  unittests/contracts/eosio.mechanics/eosmechanics.cpp
  unittests/contracts/eosio.mechanics/eosmechanics.wasm
  unittests/contracts/eosio.mechanics/mech_actions.sh
  unittests/contracts/eosio.mechanics/mech_check.sh
  unittests/contracts/eosio.mechanics/mech_loop.sh
Labels: documentation, OCI

#803 [PH] Remove unnecessary dependency on contracts.
  tests/trx_generator/CMakeLists.txt
  tests/trx_generator/main.cpp
Labels: OCI

#809 Test fix: Increase abi-serializer-max-time-ms & http-max-response-time-ms for test
  tests/plugin_http_api_test.py
Labels: OCI

#802 remove eosio-blocklog
  docs/10_utilities/eosio-blocklog.md
  docs/10_utilities/index.md
  libraries/chain/block_log.cpp
  libraries/chain/include/eosio/chain/block_log.hpp
  programs/CMakeLists.txt
  programs/eosio-blocklog/CMakeLists.txt
  programs/eosio-blocklog/main.cpp
  programs/leap-util/actions/blocklog.cpp
  programs/leap-util/actions/blocklog.hpp
  tests/TestHarness/testUtils.py
  tests/block_log_util_test.py
  tests/nodeos_snapshot_diff_test.py
  unittests/block_log_extract.cpp
Labels: documentation, OCI

#820 get_raw_block api endpoint
  libraries/chain/block_log.cpp
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/block_log.hpp
  libraries/chain/include/eosio/chain/controller.hpp
  plugins/chain_api_plugin/chain_api_plugin.cpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
  programs/cleos/httpc.hpp
  programs/cleos/main.cpp
  tests/chain_plugin_tests.cpp
  tests/plugin_http_api_test.py
Labels: documentation, OCI

#759 Programmable snapshots API
  libraries/chain/include/eosio/chain/exceptions.hpp
  plugins/producer_api_plugin/producer.swagger.yaml
  plugins/producer_api_plugin/producer_api_plugin.cpp
  plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
  plugins/producer_plugin/include/eosio/producer_plugin/snapshot_db_json.hpp
  plugins/producer_plugin/include/eosio/producer_plugin/snapshot_scheduler.hpp
  plugins/producer_plugin/producer_plugin.cpp
  plugins/producer_plugin/test/CMakeLists.txt
  plugins/producer_plugin/test/test_snapshot_scheduler.cpp
  tests/CMakeLists.txt
  tests/TestHarness/Node.py
  tests/nodeos_snapshot_diff_test.py
  tests/nodeos_snapshot_forked_test.py
Labels: documentation

#798 Remove deprecated `--private-key` option from nodeos
  docs/01_nodeos/02_usage/03_development-environment/01_local-multi-node-testnet.md
  docs/01_nodeos/03_plugins/producer_plugin/index.md
  plugins/producer_plugin/producer_plugin.cpp
  tests/TestHarness/Cluster.py
  tests/launcher.py
  tests/p2p_tests/dawn_515/test.sh
  tutorials/bios-boot-tutorial/bios-boot-tutorial.py
Labels: documentation, OCI

#818 Add TestHarness python integration scripts to dev package
  CMakeLists.txt
  package.cmake
  programs/nodeos/CMakeLists.txt
  scripts/CMakeLists.txt
  scripts/postinst
  scripts/prerm
  tests/CMakeLists.txt
  tests/TestHarness/CMakeLists.txt
  tests/TestHarness/Cluster.py
  tests/TestHarness/Node.py
  tests/TestHarness/__init__.py
  tests/TestHarness/core_symbol.py.in
  tests/TestHarness/queries.py
  tests/TestHarness/testUtils.py
  tests/TestHarness/transactions.py
  tests/block_log_util_test.py
  tests/compute_transaction_test.py
  tests/core_symbol.py.in
  tests/get_account_test.py
  tests/launcher.py
  tests/launcher_test.py
  tests/nodeos_contrl_c_test.py
  tests/nodeos_extra_packed_data_test.py
  tests/nodeos_forked_chain_test.py
  tests/nodeos_high_transaction_test.py
  tests/nodeos_retry_transaction_test.py
  tests/nodeos_run_test.py
  tests/nodeos_short_fork_take_over_test.py
  tests/nodeos_snapshot_forked_test.py
  tests/nodeos_startup_catchup.py
  tests/nodeos_under_min_avail_ram.py
  tests/nodeos_voting_test.py
  tests/prod_preactivation_test.py
  tests/read_only_trx_test.py
  tests/ship_test.py
  tests/subjective_billing_test.py
  tests/trace_plugin_test.py
  tests/trx_finality_status_forked_test.py
  tests/trx_finality_status_test.py
Labels: documentation, OCI

#869 [4.0] unshare import fix
  tests/TestHarness/Cluster.py
Labels: OCI

#864 [4.0] Test Fix: Use max-transaction-time -1
  tests/plugin_http_api_test.py
Labels: OCI

#895 set a maximum test time in CI via a ctest argument
  .github/actions/parallel-ctest-containers/action.yml
  .github/actions/parallel-ctest-containers/dist/index.mjs
  .github/actions/parallel-ctest-containers/main.mjs
  .github/workflows/build.yaml
  tests/CMakeLists.txt
Labels: CICD

#893 [3.2] Use block_num for interrupt of start_block
  plugins/net_plugin/net_plugin.cpp
  plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
  plugins/producer_plugin/producer_plugin.cpp
Labels: OCI

#908 [3.2 -> 4.0] Use block_num for interrupt of start_block
  plugins/net_plugin/net_plugin.cpp
  plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
  plugins/producer_plugin/producer_plugin.cpp
Labels: OCI

#921 [4.0] Implement support for -k/--kill in launcher.
  tests/TestHarness/Cluster.py
  tests/launcher.py
Labels: OCI

#929 [4.0 -> main] Execute read only safe tasks on read-only thread pool
  libraries/custom_appbase/include/eosio/chain/application.hpp
  libraries/custom_appbase/include/eosio/chain/exec_pri_queue.hpp
  libraries/custom_appbase/tests/custom_appbase_tests.cpp
  plugins/chain_api_plugin/chain_api_plugin.cpp
  plugins/db_size_api_plugin/db_size_api_plugin.cpp
  plugins/http_plugin/http_plugin.cpp
  plugins/http_plugin/tests/unit_tests.cpp
  plugins/net_api_plugin/net_api_plugin.cpp
  plugins/net_plugin/net_plugin.cpp
  plugins/producer_api_plugin/producer_api_plugin.cpp
  plugins/producer_plugin/producer_plugin.cpp
  plugins/producer_plugin/test/test_read_only_trx.cpp
  plugins/producer_plugin/test/test_snapshot_scheduler.cpp
  plugins/producer_plugin/test/test_trx_full.cpp
  plugins/test_control_api_plugin/test_control_api_plugin.cpp
  plugins/wallet_api_plugin/wallet_api_plugin.cpp
  programs/keosd/main.cpp
  tests/CMakeLists.txt
  tests/read_only_trx_test.py
Labels: OCI

#928 [3.2] SHiP flush logs on write
  libraries/state_history/include/eosio/state_history/log.hpp
Labels: OCI

#935 [3.2 -> 4.0] SHiP flush logs on write
  libraries/state_history/include/eosio/state_history/log.hpp
Labels: OCI

#917 [4.0] fix gelf DNS resolves to ipv6 address
  libraries/libfc/CMakeLists.txt
  libraries/libfc/include/fc/network/resolve.hpp
  libraries/libfc/include/fc/network/udp_socket.hpp
  libraries/libfc/src/log/gelf_appender.cpp
  libraries/libfc/src/network/resolve.cpp
  libraries/libfc/src/network/udp_socket.cpp
Labels: OCI

#937 [4.0 -> main] SHiP flush logs on write
  libraries/state_history/include/eosio/state_history/log.hpp
Labels: OCI

#940 [4.0->main] fix gelf DNS resolves to ipv6 address
  libraries/libfc/CMakeLists.txt
  libraries/libfc/include/fc/network/resolve.hpp
  libraries/libfc/include/fc/network/udp_socket.hpp
  libraries/libfc/src/log/gelf_appender.cpp
  libraries/libfc/src/network/resolve.cpp
  libraries/libfc/src/network/udp_socket.cpp
Labels: OCI

#915 [4.0] Clean tmp and TestLogs after test runs
  tests/TestHarness/WalletMgr.py
  tests/auto_bp_peering_test.py
  tests/cli_test.py
  tests/nodeos_contrl_c_test.py
  tests/performance_tests/performance_test_basic.py
  tests/plugin_http_api_test.py
  tests/trace_plugin_test.py
  unittests/restart_chain_tests.cpp
  unittests/snapshot_tests.cpp
Labels: OCI

#942 [4.0 -> main] Clean tmp and TestLogs after test runs
  tests/TestHarness/WalletMgr.py
  tests/auto_bp_peering_test.py
  tests/cli_test.py
  tests/nodeos_contrl_c_test.py
  tests/performance_tests/performance_test_basic.py
  tests/plugin_http_api_test.py
  tests/trace_plugin_test.py
  unittests/restart_chain_tests.cpp
  unittests/snapshot_tests.cpp
Labels: OCI

#938 [3.2 -> 4.0] forkdb reset in replay since blocks are signaled
  libraries/chain/controller.cpp
Labels: OCI
