Repository AntelopeIO/leap, pull requests merged in 2023-05, with the labels that each got.

#1112 Tests: misc cleanup
  libraries/testing/include/eosio/testing/tester.hpp
  libraries/testing/tester.cpp
  plugins/chain_plugin/test/test_account_query_db.cpp
  tests/chain_plugin_tests.cpp
  tests/get_table_seckey_tests.cpp
  tests/get_table_tests.cpp
  tests/test_chain_plugin.cpp
  unittests/api_tests.cpp
  unittests/auth_tests.cpp
  unittests/bootseq_tests.cpp
  unittests/currency_tests.cpp
  unittests/database_tests.cpp
  unittests/delay_tests.cpp
  unittests/eosio_system_tester.hpp
  unittests/misc_tests.cpp
  unittests/payloadless_tests.cpp
  unittests/producer_schedule_tests.cpp
  unittests/ram_tests.cpp
  unittests/read_only_trx_tests.cpp
  unittests/wasm-spec-tests/generated-tests/wasm_spec_tests.hpp.in
  unittests/wasm_config_tests.cpp
  unittests/wasm_tests.cpp
  unittests/whitelist_blacklist_tests.cpp
Labels: OCI

#1087 [4.0] Update swagger files to include missing doc
  plugins/chain_api_plugin/chain.swagger.yaml
Labels: documentation

#1110 [main] Update swagger files to include missing documentation
  plugins/chain_api_plugin/chain.swagger.yaml
  plugins/producer_api_plugin/producer.swagger.yaml
Labels: documentation

#1125 Remove time_point implicit conversions
  libraries/chain/apply_context.cpp
  libraries/chain/block_log.cpp
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/subjective_billing.hpp
  libraries/chain/include/eosio/chain/unapplied_transaction_queue.hpp
  libraries/libfc/include/fc/io/raw.hpp
  libraries/libfc/include/fc/time.hpp
  libraries/libfc/src/log/console_appender.cpp
  libraries/libfc/src/time.cpp
  libraries/testing/tester.cpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/chain_plugin/test/test_trx_finality_status_processing.cpp
  plugins/chain_plugin/test/test_trx_retry_db.cpp
  plugins/chain_plugin/trx_finality_status_processing.cpp
  plugins/chain_plugin/trx_retry_db.cpp
  plugins/net_plugin/net_plugin.cpp
  plugins/producer_plugin/producer_plugin.cpp
  plugins/producer_plugin/test/test_block_timing_util.cpp
  plugins/producer_plugin/test/test_read_only_trx.cpp
  plugins/producer_plugin/test/test_trx_full.cpp
  plugins/trace_api_plugin/request_handler.cpp
  plugins/trace_api_plugin/test/test_responses.cpp
  plugins/trace_api_plugin/test/test_trace_file.cpp
  programs/cleos/main.cpp
  tests/trx_generator/trx_generator.cpp
  tests/trx_generator/trx_provider.cpp
  unittests/delay_tests.cpp
  unittests/forked_tests.cpp
  unittests/misc_tests.cpp
  unittests/protocol_feature_tests.cpp
  unittests/subjective_billing_tests.cpp
  unittests/unapplied_transaction_queue_tests.cpp
  unittests/wasm_tests.cpp
Labels: OCI

#1138 [PH] Feature API Operational Mode and HTTP Transaction Generator
  tests/TestHarness/Cluster.py
  tests/TestHarness/launch_transaction_generators.py
  tests/performance_tests/CMakeLists.txt
  tests/performance_tests/README.md
  tests/performance_tests/performance_test.py
  tests/performance_tests/performance_test_basic.py
  tests/trx_generator/http_client_async.hpp
  tests/trx_generator/main.cpp
  tests/trx_generator/trx_generator.cpp
  tests/trx_generator/trx_generator.hpp
  tests/trx_generator/trx_generator_tests.cpp
  tests/trx_generator/trx_provider.cpp
  tests/trx_generator/trx_provider.hpp
Labels: OCI

#1157 Fix clang warning
  tests/trx_generator/trx_provider.hpp
Labels: OCI

#1141 [4.0] change max-retained-history-files default
  libraries/state_history/include/eosio/state_history/log.hpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
  plugins/chain_plugin/test/CMakeLists.txt
  plugins/chain_plugin/test/plugin_config_test.cpp
  plugins/state_history_plugin/include/eosio/state_history_plugin/state_history_plugin.hpp
  plugins/state_history_plugin/state_history_plugin.cpp
  plugins/state_history_plugin/tests/CMakeLists.txt
  plugins/state_history_plugin/tests/plugin_config_test.cpp
Labels: OCI

#1161 Keep `subprocess_results.log` around when test fails
  tests/TestHarness/testUtils.py
Labels: OCI

#1165 [PH] Initial reporting updates for API Node and http transaction generator
  tests/performance_tests/README.md
  tests/performance_tests/log_reader.py
  tests/performance_tests/performance_test.py
  tests/performance_tests/performance_test_basic.py
  tests/trx_generator/trx_generator.cpp
  tests/trx_generator/trx_provider.cpp
  tests/trx_generator/trx_provider.hpp
Labels: OCI

#1145 add gelf test
  tests/CMakeLists.txt
  tests/gelf_test.py
Labels: OCI

#1175 [4.0] Ignore http error on remote_endpoint() causing shutdown
  plugins/http_plugin/include/eosio/http_plugin/beast_http_listener.hpp
Labels: OCI

#1139 Update API/serialization time constraints
  libraries/chain/abi_serializer.cpp
  libraries/chain/include/eosio/chain/abi_serializer.hpp
  libraries/chain/include/eosio/chain/controller.hpp
  libraries/libfc/include/fc/io/json_relaxed.hpp
  libraries/libfc/include/fc/time.hpp
  libraries/libfc/include/fc/variant_object.hpp
  libraries/libfc/src/exception.cpp
  libraries/libfc/src/io/json.cpp
  libraries/libfc/src/log/log_message.cpp
  libraries/libfc/src/variant_object.cpp
  plugins/chain_api_plugin/chain_api_plugin.cpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
  plugins/chain_plugin/trx_retry_db.cpp
  plugins/db_size_api_plugin/db_size_api_plugin.cpp
  plugins/http_plugin/http_plugin.cpp
  plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
  plugins/http_plugin/include/eosio/http_plugin/common.hpp
  plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp
  plugins/http_plugin/include/eosio/http_plugin/macros.hpp
  plugins/http_plugin/tests/unit_tests.cpp
  plugins/net_api_plugin/net_api_plugin.cpp
  plugins/producer_api_plugin/producer.swagger.yaml
  plugins/producer_api_plugin/producer_api_plugin.cpp
  plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
  plugins/producer_plugin/producer_plugin.cpp
  plugins/test_control_api_plugin/test_control_api_plugin.cpp
  plugins/trace_api_plugin/abi_data_handler.cpp
  plugins/trace_api_plugin/include/eosio/trace_api/abi_data_handler.hpp
  plugins/trace_api_plugin/include/eosio/trace_api/request_handler.hpp
  plugins/trace_api_plugin/request_handler.cpp
  plugins/trace_api_plugin/test/test_data_handlers.cpp
  plugins/trace_api_plugin/test/test_responses.cpp
  plugins/trace_api_plugin/trace_api_plugin.cpp
  plugins/wallet_api_plugin/wallet_api_plugin.cpp
  programs/cleos/main.cpp
  programs/keosd/main.cpp
  programs/leap-util/actions/blocklog.cpp
  tests/chain_plugin_tests.cpp
  tests/plugin_http_api_test.py
  tests/trx_generator/trx_generator.cpp
  unittests/abi_tests.cpp
  unittests/wasm_tests.cpp
Labels: OCI

#1171 [4.0] Correctly handle close while syncing
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#1177 [4.0 -> main] Ignore http error on remote_endpoint() causing shutdown
  plugins/http_plugin/include/eosio/http_plugin/beast_http_listener.hpp
Labels: OCI

#1178 [4.0 -> main] Correctly handle close while syncing
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#1164 [4.0] fix replay for partitioned block log
  libraries/chain/block_log.cpp
  libraries/chain/include/eosio/chain/block_log.hpp
  libraries/chain/include/eosio/chain/log_index.hpp
  libraries/testing/tester.cpp
  plugins/chain_plugin/chain_plugin.cpp
  programs/leap-util/actions/blocklog.cpp
  tests/CMakeLists.txt
  tests/split_blocklog_replay_test.py
  unittests/block_log_extract.cpp
  unittests/partitioned_block_log_tests.cpp
Labels: OCI

#1204 [4.0] add docs/yaml content for missing chain api endpoints
  plugins/chain_api_plugin/chain.swagger.yaml
Labels: documentation

#1208 [4.0 -> main] [docs] fix devrel#248 document chain api endpoints
  plugins/chain_api_plugin/chain.swagger.yaml
Labels: documentation

#1203 IPv6 support
  libraries/libfc/include/fc/network/listener.hpp
  plugins/http_plugin/http_plugin.cpp
  plugins/http_plugin/include/eosio/http_plugin/api_category.hpp
  plugins/http_plugin/include/eosio/http_plugin/beast_http_listener.hpp
  plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp
  plugins/http_plugin/include/eosio/http_plugin/common.hpp
  plugins/http_plugin/tests/unit_tests.cpp
  plugins/net_plugin/net_plugin.cpp
  plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp
  plugins/state_history_plugin/state_history_plugin.cpp
  plugins/state_history_plugin/tests/session_test.cpp
Labels: OCI

#1195 [PH] Performance Harness improvements
  tests/performance_tests/CMakeLists.txt
  tests/performance_tests/README.md
  tests/performance_tests/log_reader.py
  tests/performance_tests/performance_test.py
  tests/performance_tests/performance_test_basic.py
  tests/trx_generator/trx_provider.hpp
Labels: OCI

#1187 P2P Refactor connections management
  plugins/net_plugin/include/eosio/net_plugin/auto_bp_peering.hpp
  plugins/net_plugin/net_plugin.cpp
  plugins/net_plugin/tests/auto_bp_peering_unittest.cpp
Labels: OCI

#1210 Add prettyPrint and printReturnLimit to processUrllibRequest()
  tests/TestHarness/queries.py
Labels: OCI

#1209 Remove disable-subjective-billing option
  docs/01_nodeos/03_plugins/producer_plugin/index.md
  plugins/producer_plugin/producer_plugin.cpp
  plugins/producer_plugin/test/test_options.cpp
  plugins/producer_plugin/test/test_read_only_trx.cpp
  plugins/producer_plugin/test/test_trx_full.cpp
  tests/performance_tests/performance_test_basic.py
  tests/test_snapshot_scheduler.cpp
Labels: documentation, OCI

#1215 P2P sync improvements
  plugins/net_plugin/net_plugin.cpp
Labels: documentation, OCI
