Repository AntelopeIO/leap, pull requests merged in 2023-12, with the labels that each got.

#1954 [5.0] Return error for num == 0 for bls_g1_weighted_sum, bls_g2_weighted_sum and bls_pairing
  libraries/chain/webassembly/crypto.cpp
  unittests/bls_primitives_tests.cpp
  unittests/test-contracts/bls_primitives_test/bls_primitives_test.cpp
  unittests/test-contracts/bls_primitives_test/bls_primitives_test.wasm
Labels: OCI, consensus

#1955 IF: merkle calculation for transaction_mroot and action_mroot
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/merkle.hpp
  libraries/chain/merkle.cpp
  unittests/merkle_tree_tests.cpp
Labels: OCI

#1972 [5.0] fix `experimental-binaries` creation on releases: lowercase org name in image tag
  .github/workflows/release.yaml
Labels: CICD

#1977 [5.0 -> main] fix `experimental-binaries` creation on releases: lowercase org name in image tag
  .github/workflows/release.yaml
Labels: CICD

#1984 [5.0] Extra info level logging
  libraries/chain/controller.cpp
  plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp
Labels: OCI

#1988 [5.0 -> main] Extra info level logging
  libraries/chain/controller.cpp
  plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp
Labels: OCI

#1986 [5.0] Add BLS_PRIMITIVES2 to bios-boot-tutorial.py
  tutorials/bios-boot-tutorial/bios-boot-tutorial.py
Labels: OCI

#2001 [5.0 -> main] Add BLS_PRIMITIVES2 to bios-boot-tutorial.py
  tutorials/bios-boot-tutorial/bios-boot-tutorial.py
Labels: OCI

#2000 [5.0] Test: Fix trx_generator handling of connection lost
  tests/trx_generator/trx_provider.cpp
Labels: OCI

#2004 IF: Use `set_finalizer` type names that match `eosio.bios` and CDT
  libraries/chain/hotstuff/test/test_hotstuff.cpp
  libraries/chain/include/eosio/chain/hotstuff/finalizer_authority.hpp
  libraries/chain/include/eosio/chain/hotstuff/finalizer_policy.hpp
  libraries/chain/webassembly/privileged.cpp
  unittests/api_tests.cpp
Labels: OCI

#1998 IF: Add IF activation to integration test framework
  libraries/chain/hotstuff/chain_pacemaker.cpp
  tests/TestHarness/Cluster.py
  tests/TestHarness/TestHelper.py
  tests/TestHarness/accounts.py
  tests/TestHarness/launcher.py
  tests/TestHarness/logging-template.json
  tests/distributed-transactions-test.py
  tests/nodeos_chainbase_allocation_test.py
  tests/nodeos_extra_packed_data_test.py
  tests/nodeos_producer_watermark_test.py
  tests/nodeos_run_test.py
  tests/prod_preactivation_test.py
  tutorials/bios-boot-tutorial/bios-boot-tutorial.py
  unittests/contracts/CMakeLists.txt
  unittests/contracts/eosio.boot/CMakeLists.txt
  unittests/contracts/eosio.boot/eosio.boot.abi
  unittests/contracts/eosio.boot/eosio.boot.cpp
  unittests/contracts/eosio.boot/eosio.boot.hpp
  unittests/contracts/eosio.boot/eosio.boot.wasm
Labels: OCI

#2005 IF: Fix merge issue on hotstuff_integration
  libraries/chain/hotstuff/chain_pacemaker.cpp
Labels: OCI

#2002 [5.0 -> main] Test: Fix trx_generator handling of connection lost
  tests/trx_generator/trx_provider.cpp
Labels: OCI

#2007 [5.0] Fix unlinkable block exceptions when block-log-retain-blocks = 0
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#2009 [5.0 -> main] Fix unlinkable block exceptions when block-log-retain-blocks = 0
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#2008 [5.0] Test: Check for unlinkable blocks while syncing
  tests/nodeos_startup_catchup.py
Labels: OCI

#2015 [5.0] Test: Check for unlinkable blocks while syncing - 2
  tests/nodeos_startup_catchup.py
Labels: OCI

#2014 [5.0 -> main] Test: Check for unlinkable blocks while syncing
  tests/nodeos_startup_catchup.py
Labels: OCI

#2013 IF: Remove block_state_legacy access
  libraries/chain/controller.cpp
  libraries/chain/hotstuff/chain_pacemaker.cpp
  libraries/chain/include/eosio/chain/controller.hpp
  libraries/chain/include/eosio/chain/producer_schedule.hpp
  libraries/testing/include/eosio/testing/tester.hpp
  libraries/testing/tester.cpp
  plugins/chain_api_plugin/chain.swagger.yaml
  plugins/chain_api_plugin/chain_api_plugin.cpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
  plugins/net_plugin/net_plugin.cpp
  plugins/producer_plugin/producer_plugin.cpp
  plugins/state_history_plugin/state_history_plugin.cpp
  plugins/test_control_plugin/test_control_plugin.cpp
  programs/cleos/httpc.hpp
  programs/cleos/main.cpp
  tests/plugin_http_api_test.py
  tests/test_chain_plugin.cpp
  unittests/block_tests.cpp
  unittests/bootseq_tests.cpp
  unittests/chain_tests.cpp
  unittests/database_tests.cpp
  unittests/eosio_system_tester.hpp
  unittests/forked_tests.cpp
  unittests/producer_schedule_tests.cpp
  unittests/protocol_feature_tests.cpp
  unittests/special_accounts_tests.cpp
Labels: OCI

#2018 switch to using reference-contracts in libtester tests
  .cicd/defaults.json
  .github/workflows/build.yaml
Labels: CICD
